services:
  postgres:
    image: postgres:17.4-alpine
    container_name: postgres
    hostname: postgres
    profiles: [ "db" ]
    restart: always
    environment:
      TZ: Europe/Warsaw
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    ports:
#      - "host_port:container_port"
      - "127.0.0.1:25432:5432"
    volumes:
      - stockprices_data:/var/lib/postgresql/data
      - ./sql-scripts:/docker-entrypoint-initdb.d
    networks:
      - stockprices_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U stockpriceuser -d predictstockprices_db" ]
      interval: 10s
      retries: 5
      start_period: 5s
  mail:
    container_name: mail
    image: axllent/mailpit
    networks:
      - stockprices_network
    ports:
      - '8125:8025'
      - '1125:1025'

volumes:
  stockprices_data:

networks:
  stockprices_network:
    driver: bridge