@domainName = master
##########################
POST http://localhost:8080/domains/{{domainName}}/auth/token
Accept: application/json
Content-Type: application/json

{
  "type": "password",
  "username": "superAdmin",
  "password": "superAdminPassword"
}

> {%
    client.global.set('accessToken', response.body.accessToken);
    client.global.set('refreshToken', response.body.refreshToken)
%}

##########################
POST http://localhost:8080/domains/{{domainName}}/auth/token
Accept: application/json
Content-Type: application/json

{
  "type": "refresh-token",
  "token": "{{refreshToken}}"
}

> {%
    client.global.set('accessToken', response.body.accessToken);
    client.global.set('refreshToken', response.body.refreshToken)
%}

##########################
POST http://localhost:8080/domains/upload
Authorization: Bearer {{accessToken}}
Content-Type: multipart/form-data; boundary=boundary123

--boundary123
Content-Disposition: form-data; name="file"; filename="importDomainTest.json"
Content-Type: application/json

< D:/jakub/Desktop/PredictStock/secureauth/src/test/resources/upload/importDomainTest.json
--boundary123--

##########################
POST http://localhost:8080/domains/{{domainName}}/auth/register
Accept: application/json
Content-Type: application/json

{
  "username": "test7432",
  "email": "test743@gmail.com",
  "password": "sectret123"
}


