server:
  port: 8080

spring:
  application:
    name: auth

  datasource:
    url: jdbc:postgresql://localhost:25432/predictstockprices_db?currentSchema=secureauth
    username: stockpriceuser
    password: secret1!
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: secureauth
        format_sql: true
        show_sql: true
    show-sql: true

  docker:
    compose:
      enabled: false
