server:
  port: 8080
  forward-headers-strategy: native

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
    config-url: /api-secure-auth-backend/swagger-config
    disable-swagger-default-url: true
    url: /api-secure-auth-backend
  api-docs:
    enabled: true
    path: /api-secure-auth-backend

spring:
  flyway:
    baseline-on-migrate: true
    enabled: true
    out-of-order: true
    schemas: secureauth
    locations: classpath:db/migration

  application:
    name: auth

  config:
    import: optional:configtree:/run/secrets/

  datasource:
    url: jdbc:postgresql://${DB_HOSTNAME}:${DB_PORT}/${DB_NAME}?currentSchema=secureauth
    username: ${DB_USER}
    password: ${secureauth.db.password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: secureauth
        format_sql: true
        show_sql: true
    show-sql: true

  mail:
    host: localhost
    port: 1125

  docker:
    compose:
      enabled: false

secureauth:
  main:
    domain: ${SECURE_MAIN_DOMAIN:master}
    user: ${SECUREAUTH_ADMIN_USER:}
    email: ${SECUREAUTH_ADMIN_EMAIL:}
    password: ${SECUREAUTH_ADMIN_PASSWORD:}
  mail:
    notificationEmail: notification@test.com
    activeAccountTemplate: active-email.ftl
    activationPath: /domains/%s/auth/account/activate?token=%s
  job:
    cron:
      refreshTokenCleanup: 0 0 2 * * *
      emailTokenCleanup: 0 0 1 * * *
      sessionCleanup: 0 0 3 * * *

shedlock:
  enabled: true
