TRUNCATE TABLE secureauth.user_role CASCADE;
TRUNCATE TABLE secureauth.role CASCADE;
TRUNCATE TABLE secureauth.password CASCADE;
TRUNCATE TABLE secureauth.user CASCADE;
TRUNCATE TABLE secureauth.key CASCADE;
TRUNCATE TABLE secureauth.session CASCADE;
TRUNCATE TABLE secureauth.refresh_token CASCADE;
TRUNCATE TABLE secureauth.email_verification_token CASCADE;
TRUNCATE TABLE secureauth.domain CASCADE;